### ISSUE TITLE
warning msg on calculating AD ratio issue

### ISSUE THREAD

**Issue by Wang-Jing-NZ** [phe-bioinformatics/snapperdb#11]
A warning message like this:
WARNING: Could not calculate AD ratio from Record(CHROM=gi|15829254|ref|NC_002695.1|, POS=267176, REF=C, ALT=[G, T]) POS: 267176

Can you provide some insight of this warning message? I am trying to understand this msg's implication, if this will be called as a SNP? I noticed Tim opened an issue last year about mixed positions allowed cutoff, are they related?

**Comment by ulfschaefer** [comment]
The AD ratio cannot be calculated if there are two different ref bases called. If you filter your vcf on the AD ratio, this position will fail that filter, so an N would be put in at that position.
