### ISSUE TITLE
Versions of additionals tools

### ISSUE THREAD

**Issue by ConstantinV** [phe-bioinformatics/snapperdb#13]
Thanks a lot for your tool! 
Now I'm trying to install and run it. I have trouble with GATK while creating VCF. I think I use the wrong version of GATK. Could you please include the actual versions for 
Postgres
Samtools
Picard
GATK
BWA
Thank you!

**Comment by ulfschaefer** [comment]
We use the following versions in the variant calling:
samtools/1.1
picard-tools/1.111
gatk/2.6.5
bwa/0.7.12
Whether it works with newer versions needs to be tested. I suspect it wouldn't for GATK and Samtools, but should be OK for others.

For postgres we use a number of subversions of major version 9 that should all work.

Hope this helps.

**Comment by ConstantinV** [comment]
Now it is clear. Thank you!
