### ISSUE TITLE
rec_file option

### ISSUE THREAD

**Issue by ConstantinV** [phe-bioinformatics/snapperdb#15]
Hello,
I saw a rec_file option in run_snapperdb.py get_the_snps command.
I suppose this file with regions where SNPs can be excluded. 
If yes, could you describe the format of the file in details?

Thank you!

**Comment by timdallman** [comment]
Hi.
The '-n' option in get_the_snps expects a file with tab separated regions to ignore in the format:
chromosome/contig<tab>start pos<tab>end pos<tab>
e.g.
gi|15829254|ref|NC_002695.1 50 500
gi|15829254|ref|NC_002695.1 1250 1700
.....

**Comment by ConstantinV** [comment]
Thank you a lot!
