### ISSUE TITLE
Possible to work with MySQL?

### ISSUE THREAD

**Issue by Wang-Jing-NZ** [phe-bioinformatics/snapperdb#16]
Hi Tim and your fellow bioinformaticians,

Is it possible to use MySQL as the back-end DBMS for snapperDB? We are running a mysql server already on the server on which the snapperDB will be installed and configured. So we would like to find out if it is possible to use MySQL instead. 

Regards,
Jing

**Comment by timdallman** [comment]
Hi Jin.
Currently snapperdb only supports postgres 
Thanks,
Tim
