### ISSUE TITLE
Which snapperdb.py should i be calling?

### ISSUE THREAD

**Issue by jb2cool** [phe-bioinformatics/snapperdb#8]
On my system I have two different snapperdb.py files. I have one in ~/snapperdb and one in /usr/bin. I think I need to use the one in ~/snapperdb (This one seems to do something more productive) but what's the purpose of the other one?

The reason I ask is that currently I have to be in the ~/snapperdb directory and call this as ./snapperdb.py but it would be nice if I could be in any directory and just call it as snapperdb or snapperdb.py

If I need to be in the directory for relative paths to work then that's absolutely fine, I just need to know that I'm calling the right script.

**Comment by timdallman** [comment]
Please use relative paths - we are working on getting the /usr/bin one to load the modules correctly

**Comment by jb2cool** [comment]
So for now run ./snapperdb.py directly from the ~/snapperdb directory?

I think you are coming to my site tomorrow, i'll try to say hi.

**Comment by timdallman** [comment]
Either run from installation directory or use complete installation path.
Great if we can meet tomorrow
T

**Comment by jb2cool** [comment]
Thanks for clarifying
